Time::DATE_FORMATS[:default] = '%A, %d, %b %Y'
Time::DATE_FORMATS[:default_with_time] = '%A, %d %b %Y %I:%M %p'
Time::DATE_FORMATS[:with_time] = '%A, %d, %b %Y %H:%M %p'
Date::DATE_FORMATS[:default] = '%A, %d, %b %Y'
Time::DATE_FORMATS[:date_only] = '%d, %b %Y'
Date::DATE_FORMATS[:date_only] = '%d, %b %Y'
Time::DATE_FORMATS[:count_down] = '%Y/%m/%d %H:%M'
